version: '3'

networks:
  network:
    driver: bridge
services:
  app:
    build: .
    image: agenda
    container_name: node_api_agenda
    volumes:
      - ./pictures/:/app/pictures/
    depends_on:
      - db
    ports:
      - '3000:3000'
    networks:
      - network
    environment:
      - PORT=3000
      - DB_HOST=docker_mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=root
      - DB_DLCT=mysql
      - DB_NAME=agenda
      - USER_FOTOS_DIRECTORY=/app/pictures/
      - DEFAULT_PROFILE_PICTURE=/app/default-user-image.png
      - NODE_ENV=production
  db:
    image: mysql:8.0.27
    container_name: docker_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3308:3306
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=America/Sao_Paulo
    networks:
      - network